"""The response models in aeronexus_api.schemas must describe exactly what the endpoints return (spec §10.3)."""
from __future__ import annotations

from aeronexus_api.schemas import CommittedOut, HealthOut, InstanceRowOut, MetricsOut, RunRowOut, TimelineOut


def test_health_instances_and_metrics_match_schemas(api_client):
    HealthOut.model_validate(api_client.get("/health").json())
    MetricsOut.model_validate(api_client.get("/config/metrics").json())
    r = api_client.post("/data/generate", json={"size": "small", "seed": 3, "disruptions": ["fog:DEL"]})
    assert r.status_code == 200, r.text
    rows = api_client.get("/data/instances").json()
    assert [InstanceRowOut.model_validate(x).id for x in rows] == [r.json()["id"]]


def test_timeline_runs_and_committed_match_schemas(api_client):
    iid = api_client.post("/data/generate", json={"size": "small", "seed": 3, "disruptions": ["fog:DEL"]}).json()["id"]
    tl = TimelineOut.model_validate(api_client.get("/timeline", params={"instance_id": iid, "t": 300}).json())
    assert tl.summary.flights == len(tl.flights) and tl.clock == 300
    run = api_client.post("/recommend", json={"instance_id": iid, "decision_time": 300, "seed": 1}).json()
    after = api_client.post("/timeline/plan", json={"instance_id": iid, "decision_time": 300, "actions": run["plans"][0]["actions"]})
    assert after.status_code == 200, after.text
    TimelineOut.model_validate(after.json())
    rows = api_client.get("/runs", params={"instance_id": iid}).json()
    assert [RunRowOut.model_validate(x).id for x in rows] == [run["id"]]
    CommittedOut.model_validate(api_client.get(f"/data/instances/{iid}/committed").json())


def test_openapi_names_every_console_payload(api_client):
    doc = api_client.get("/openapi.json").json()
    names = set(doc["components"]["schemas"])
    for n in ("HealthOut", "TimelineOut", "TimelineFlightOut", "RunRowOut", "InstanceRowOut", "CommittedOut", "MetricsOut", "Run", "ConfigEnvelope"):
        assert n in names, n


def test_exported_openapi_is_current():
    """apps/occ/openapi.json is generated by scripts/export_openapi.py; the console's types come from it."""
    import importlib.util
    from pathlib import Path

    spec = importlib.util.spec_from_file_location("export_openapi", Path(__file__).resolve().parents[1] / "scripts" / "export_openapi.py")
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    assert mod.main(["--check"]) == 0
