/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/benchmark/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Benchmark */
        get: operations["latest_benchmark_benchmark_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/benchmark/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Bench
         * @description Small ladder run so the current configuration can be checked from the UI; the full 30-scenario run
         *     stays a CLI job (python -m aeronexus_core.benchmark).
         */
        post: operations["run_bench_benchmark_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cases */
        get: operations["list_cases_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Cases */
        get: operations["latest_cases_cases_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Cases */
        post: operations["run_cases_cases_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/constraints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Constraints */
        put: operations["put_constraints_config_constraints_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/hash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Hash */
        get: operations["get_hash_config_hash_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metric Names */
        get: operations["metric_names_config_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/parameters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Parameters */
        put: operations["put_parameters_config_parameters_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plugins */
        get: operations["plugins_config_plugins_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Presets */
        get: operations["presets_config_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/presets/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Preset */
        post: operations["save_preset_config_presets__name__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/presets/{name}/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Load Preset */
        post: operations["load_preset_config_presets__name__load_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset From Yaml
         * @description Reload the YAML registries from disk (developer convenience).
         */
        post: operations["reset_from_yaml_config_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Search */
        put: operations["put_search_config_search_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Terms */
        put: operations["put_terms_config_terms_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate
         * @description Dry-run terms/constraints against a sample namespace without saving (§15.3).
         */
        post: operations["validate_config_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Instance */
        post: operations["generate_instance_data_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Instance
         * @description Import a full instance JSON (the generator's format; also the target for CSV import in Phase 4).
         */
        post: operations["import_instance_data_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Instances */
        get: operations["list_instances_data_instances_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/instances/{iid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Instance */
        get: operations["get_instance_data_instances__iid__get"];
        put?: never;
        post?: never;
        /** Delete Instance */
        delete: operations["delete_instance_data_instances__iid__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/instances/{iid}/columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Column */
        post: operations["add_column_data_instances__iid__columns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/instances/{iid}/committed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Committed */
        get: operations["get_committed_data_instances__iid__committed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/instances/{iid}/committed/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Committed
         * @description Clear today's committed decisions (undo all accepted plans); runs keep their record.
         */
        post: operations["reset_committed_data_instances__iid__committed_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/instances/{iid}/disruptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Disruption */
        post: operations["add_disruption_data_instances__iid__disruptions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/instances/{iid}/disruptions/{did}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Disruption */
        delete: operations["remove_disruption_data_instances__iid__disruptions__did__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/instances/{iid}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Summary */
        get: operations["get_summary_data_instances__iid__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/instances/{iid}/table/{entity}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Table
         * @description Rows with attributes flattened (prefixed ``attr:``) plus the column list, for the database-style UI.
         */
        get: operations["table_data_instances__iid__table__entity__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/data/instances/{iid}/{entity}/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Row */
        patch: operations["patch_row_data_instances__iid___entity___key__patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Recommend */
        post: operations["post_recommend_recommend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide */
        post: operations["decide_runs__run_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get State
         * @description Snapshot at decision time ``t`` (minutes from day start). Phase 1 projects known delays into etd/eta.
         */
        get: operations["get_state_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Timeline
         * @description Baseline ("do nothing") propagation at decision time t: per-flight outcomes for the rotation view.
         */
        get: operations["timeline_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/timeline/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Plan Timeline
         * @description Per-flight outcomes of the day once ``actions`` are applied at ``decision_time`` (the after view).
         */
        post: operations["plan_timeline_timeline_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whatif": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Whatif
         * @description Evaluate a controller-chosen plan on the same engine and compare it with the recommendation.
         */
        post: operations["post_whatif_whatif_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Action */
        Action: {
            feasibility?: components["schemas"]["Feasibility"];
            /** Metrics */
            metrics?: {
                [key: string]: number;
            };
            /** Params */
            params?: {
                [key: string]: unknown;
            };
            /** Target Flights */
            target_flights: string[];
            /**
             * Type
             * @enum {string}
             */
            type: "CANCEL_LEG" | "CANCEL_CYCLE" | "DELAY" | "SWAP" | "WAIT";
        };
        /** Aircraft */
        Aircraft: {
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            };
            /** Location */
            location?: string | null;
            /** Maintenance Due At */
            maintenance_due_at?: number | null;
            /** Mel Restrictions */
            mel_restrictions?: string[];
            /**
             * Status
             * @default OK
             * @enum {string}
             */
            status: "OK" | "AOG" | "MEL";
            /** Tail */
            tail: string;
            /** Type Code */
            type_code: string;
        };
        /** AircraftType */
        AircraftType: {
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            };
            /**
             * Cat3 Capable
             * @default true
             */
            cat3_capable: boolean;
            /** Code */
            code: string;
            /**
             * Cruise Kmh
             * @default 750
             */
            cruise_kmh: number;
            /**
             * Hourly Operating Cost
             * @default 0
             */
            hourly_operating_cost: number;
            /** Min Turnaround Min */
            min_turnaround_min?: {
                [key: string]: number;
            };
            /** Seats */
            seats: number;
        };
        /** Airport */
        Airport: {
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            };
            /** Closure Windows */
            closure_windows?: components["schemas"]["TimeWindow"][];
            /** Code */
            code: string;
            /** Curfew Windows */
            curfew_windows?: components["schemas"]["TimeWindow"][];
            /**
             * Is Hub
             * @default false
             */
            is_hub: boolean;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Lvp Windows */
            lvp_windows?: components["schemas"]["TimeWindow"][];
            /**
             * Min Connection Time Min
             * @default 45
             */
            min_connection_time_min: number;
            /** Name */
            name: string;
            slot_capacity_per_hour?: components["schemas"]["HourlyCapacity"];
            /**
             * Stand Capacity
             * @default 20
             */
            stand_capacity: number;
            /**
             * Tz
             * @default Asia/Kolkata
             */
            tz: string;
        };
        /** AtRiskOut */
        AtRiskOut: {
            /**
             * Delay Min
             * @default 0
             */
            delay_min: number;
            /** Flight */
            flight: string;
            /**
             * Forced
             * @default false
             */
            forced: boolean;
            /** Reasons */
            reasons: string[];
        };
        /** BenchmarkOut */
        BenchmarkOut: {
            /** Block Sigma */
            block_sigma?: number | null;
            /** Config Hash */
            config_hash: string;
            /** Created At */
            created_at: string;
            /** Current Config Hash */
            current_config_hash: string;
            /** Records */
            records: components["schemas"]["BenchmarkRecordOut"][];
            /** S Eval */
            s_eval: number;
            /** Scenarios */
            scenarios: number;
            /** Seed */
            seed?: number | null;
            /** Stale */
            stale: boolean;
            /** Summary */
            summary: {
                [key: string]: components["schemas"]["PolicySummaryOut"];
            };
        };
        /** BenchmarkRecordOut */
        BenchmarkRecordOut: {
            /** At Risk */
            at_risk: number;
            /** Baseline Forced */
            baseline_forced: number;
            /** Clock */
            clock: number;
            /** Disruption */
            disruption: string;
            /** Name */
            name: string;
            /** Policies */
            policies: {
                [key: string]: components["schemas"]["PolicyOutcomeOut"];
            };
            /** Size */
            size: string;
        };
        /** BenchmarkRunRequest */
        BenchmarkRunRequest: {
            /**
             * S Eval
             * @default 20
             */
            s_eval: number;
            /**
             * Save
             * @default false
             */
            save: boolean;
            /**
             * Scenarios
             * @default 4
             */
            scenarios: number;
            /**
             * Seed
             * @default 2026
             */
            seed: number;
            /**
             * Use Surrogate
             * @default true
             */
            use_surrogate: boolean;
        };
        /** CaseDefOut */
        CaseDefOut: {
            /**
             * Base
             * @default tiny
             */
            base: string;
            /**
             * Decision Time
             * @default 0
             */
            decision_time: number;
            /** Disruptions */
            disruptions?: string[];
            /** Expected */
            expected?: string[];
            /** Id */
            id: string;
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /** Title */
            title: string;
        };
        /** CaseExcludedOut */
        CaseExcludedOut: {
            /** Key */
            key: string;
            /** Reasons */
            reasons?: string[];
        };
        /** CasePlanOut */
        CasePlanOut: {
            /** Actions */
            actions?: string[];
            /** Nis */
            nis: number;
            /** Rank */
            rank?: number | null;
        };
        /** CaseResultOut */
        CaseResultOut: {
            /** Baseline Forced */
            baseline_forced?: number | null;
            /** Checks */
            checks?: string[];
            /** Excluded */
            excluded?: components["schemas"]["CaseExcludedOut"][];
            /** Expected */
            expected?: string[];
            /** Failures */
            failures?: string[];
            /** Id */
            id: string;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
            /** Matched */
            matched: string;
            /** Nis */
            nis?: number | null;
            /** Passed */
            passed: boolean;
            /** Plan Forced */
            plan_forced?: number | null;
            /** Plans */
            plans?: components["schemas"]["CasePlanOut"][];
            /**
             * Plans Evaluated
             * @default 0
             */
            plans_evaluated: number;
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /** Title */
            title: string;
            /** Top1 */
            top1?: string[];
            /** Top Reasons */
            top_reasons?: string[];
        };
        /** CasesRunOut */
        CasesRunOut: {
            /** Config Hash */
            config_hash: string;
            /** Config Version */
            config_version: number;
            /** Elapsed Ms */
            elapsed_ms: number;
            /** Passed */
            passed: number;
            /** Results */
            results: components["schemas"]["CaseResultOut"][];
            /** Total */
            total: number;
            /** Use Surrogate */
            use_surrogate: boolean;
        };
        /** CasesRunRequest */
        CasesRunRequest: {
            /**
             * Ids
             * @description subset of case ids; empty = all
             */
            ids?: string[];
            /**
             * Use Surrogate
             * @default false
             */
            use_surrogate: boolean;
        };
        /** ColumnRequest */
        ColumnRequest: {
            /**
             * Default
             * @default 0
             */
            default: unknown;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Entity
             * @enum {string}
             */
            entity: "flights" | "aircraft" | "crews" | "airports" | "itineraries";
            /** Name */
            name: string;
            /**
             * Type
             * @default number
             * @enum {string}
             */
            type: "number" | "bool" | "text";
        };
        /** CommittedOut */
        CommittedOut: {
            /** Cancelled */
            cancelled: string[];
            /** Count */
            count: number;
            /** Delays */
            delays: {
                [key: string]: number;
            };
            /** Labels */
            labels: string[];
            /** Swaps */
            swaps: string[];
            /** Tail Override */
            tail_override: {
                [key: string]: string;
            };
        };
        /** ConfigEnvelope */
        ConfigEnvelope: {
            config: components["schemas"]["EngineConfig"];
            /** Hash */
            hash: string;
            /** Updated At */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** ConstraintDef */
        ConstraintDef: {
            /** Config */
            config?: {
                [key: string]: unknown;
            };
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Id */
            id: string;
            /**
             * Kind
             * @default builtin
             * @enum {string}
             */
            kind: "builtin" | "expression";
            /** Name */
            name: string;
            /** Plugin */
            plugin?: string | null;
            /**
             * Severity
             * @default hard
             * @constant
             */
            severity: "hard";
        };
        /**
         * Crew
         * @description One crew set (cockpit + cabin as a unit; decision Q6) with cockpit qualification flags.
         */
        Crew: {
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            };
            /** Base */
            base: string;
            /**
             * Callout Min
             * @default 90
             */
            callout_min: number;
            /** Duty Start */
            duty_start?: number | null;
            /** Fdp Limit Min */
            fdp_limit_min: number;
            /**
             * Flight Time Today Min
             * @default 0
             */
            flight_time_today_min: number;
            /**
             * Flight Time Week Min
             * @default 0
             */
            flight_time_week_min: number;
            /** Id */
            id: string;
            /**
             * Is Standby
             * @default false
             */
            is_standby: boolean;
            /** Location */
            location: string;
            /** Pairing */
            pairing?: string[];
            /**
             * Rest Until
             * @default 0
             */
            rest_until: number;
            /** Special Quals */
            special_quals?: string[];
            /** Type Ratings */
            type_ratings: string[];
        };
        /** DecisionRequest */
        DecisionRequest: {
            /** Accepted Plan */
            accepted_plan?: number | null;
            /** Override Reason */
            override_reason?: string | null;
        };
        /**
         * Decisions
         * @description The plan-so-far as an overlay on the immutable instance (Plan §7). Applying an action extends this;
         *     the simulator derives the effective schedule from instance + decisions + disruptions.
         */
        Decisions: {
            /** Cancelled */
            cancelled?: string[];
            /** Crew Override */
            crew_override?: {
                [key: string]: string;
            };
            /** Delays */
            delays?: {
                [key: string]: number;
            };
            /** Swaps */
            swaps?: string[];
            /** Tail Override */
            tail_override?: {
                [key: string]: string;
            };
            /** Wait Until */
            wait_until?: number | null;
        };
        /** DeletedOut */
        DeletedOut: {
            /** Deleted */
            deleted: string;
        };
        /** Disruption */
        Disruption: {
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            };
            /** End Distribution */
            end_distribution?: {
                [key: string]: unknown;
            } | null;
            /** End Nominal */
            end_nominal?: number | null;
            /** Id */
            id: string;
            /** Severity */
            severity?: {
                [key: string]: unknown;
            };
            /** Start */
            start: number;
            /** Target */
            target: string;
            /**
             * Type
             * @enum {string}
             */
            type: "AIRPORT_CAPACITY" | "LVP" | "AOG" | "CREW_UNAVAILABLE" | "ATC_FLOW" | "FLIGHT_DELAY" | "CLOSURE";
        };
        /** DisruptionRequest */
        DisruptionRequest: {
            disruption?: components["schemas"]["Disruption"] | null;
            /**
             * Spec
             * @description CLI-style spec, e.g. fog:DEL:300:240:0.4
             */
            spec?: string | null;
        };
        /** EngineConfig */
        EngineConfig: {
            /** Constraints */
            constraints?: components["schemas"]["ConstraintDef"][];
            /** Objective Terms */
            objective_terms?: components["schemas"]["ObjectiveTerm"][];
            /** Parameters */
            parameters?: components["schemas"]["ParameterDef"][];
            /**
             * Preset Name
             * @default default
             */
            preset_name: string;
            search?: components["schemas"]["SearchSettings"];
        };
        /** Feasibility */
        Feasibility: {
            /** Reasons */
            reasons?: string[];
            /**
             * Status
             * @default unchecked
             * @enum {string}
             */
            status: "feasible" | "infeasible" | "unchecked";
        };
        /** Flight */
        Flight: {
            /** Aircraft Type */
            aircraft_type: string;
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            };
            /** Block Min */
            block_min: number;
            /**
             * Booked Pax
             * @default 0
             */
            booked_pax: number;
            /** Crew Id */
            crew_id?: string | null;
            /**
             * Delay Min
             * @default 0
             */
            delay_min: number;
            /** Dest */
            dest: string;
            /** Eta */
            eta?: number | null;
            /** Etd */
            etd?: number | null;
            /** Id */
            id: string;
            /** Number */
            number: string;
            /** Origin */
            origin: string;
            /**
             * Pax Connecting
             * @default 0
             */
            pax_connecting: number;
            /**
             * Pax High Value
             * @default 0
             */
            pax_high_value: number;
            /**
             * Pax Partner
             * @default 0
             */
            pax_partner: number;
            /**
             * Pax Special Assistance
             * @default 0
             */
            pax_special_assistance: number;
            /**
             * Protected
             * @default false
             */
            protected: boolean;
            /** Protection Reason */
            protection_reason?: string | null;
            /** Seats */
            seats: number;
            /** Sta */
            sta: number;
            /**
             * Status
             * @default SCHEDULED
             * @enum {string}
             */
            status: "SCHEDULED" | "DELAYED" | "DEPARTED" | "ARRIVED" | "CANCELLED";
            /** Std */
            std: number;
            /** Tail */
            tail?: string | null;
        };
        /** GenerateRequest */
        GenerateRequest: {
            /**
             * Disruptions
             * @description CLI-style specs, e.g. fog:DEL, aog:VT-IAB:600
             */
            disruptions?: string[];
            /**
             * Overrides
             * @description GeneratorParams field overrides
             */
            overrides?: {
                [key: string]: unknown;
            };
            /**
             * Seed
             * @default 1
             */
            seed: number;
            /**
             * Size
             * @default small
             * @enum {string}
             */
            size: "small" | "medium" | "large";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Config Hash */
            config_hash: string;
            /** Config Version */
            config_version: number;
            /** Engine Version */
            engine_version: string;
            narration: components["schemas"]["NarrationStatus"];
            /** Narration Enabled */
            narration_enabled: boolean;
            /** Status */
            status: string;
            /** Write Key Required */
            write_key_required: boolean;
        };
        /** HourlyCapacity */
        HourlyCapacity: {
            /** Arr */
            arr: number;
            /** Dep */
            dep: number;
        };
        /** Instance */
        Instance: {
            /** Aircraft */
            aircraft: components["schemas"]["Aircraft"][];
            /** Aircraft Types */
            aircraft_types: components["schemas"]["AircraftType"][];
            /** Airports */
            airports: components["schemas"]["Airport"][];
            committed?: components["schemas"]["Decisions"];
            /** Crews */
            crews: components["schemas"]["Crew"][];
            /**
             * Day Start
             * Format: date
             */
            day_start: string;
            /** Disruptions */
            disruptions?: components["schemas"]["Disruption"][];
            /** Flights */
            flights: components["schemas"]["Flight"][];
            /** Itineraries */
            itineraries: components["schemas"]["Itinerary"][];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /** Seed */
            seed?: number | null;
            /**
             * Size
             * @default custom
             * @enum {string}
             */
            size: "small" | "medium" | "large" | "custom";
        };
        /** InstanceCreated */
        InstanceCreated: {
            /** Id */
            id: string;
            /** Issues */
            issues: string[];
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
        };
        /** InstanceRowOut */
        InstanceRowOut: {
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Seed */
            seed?: number | null;
            /** Size */
            size: string;
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
        };
        /** Itinerary */
        Itinerary: {
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            };
            /**
             * Category
             * @default local
             * @enum {string}
             */
            category: "local" | "connecting" | "partner";
            /** Id */
            id: string;
            /** Legs */
            legs: string[];
            /** Pax Count */
            pax_count: number;
        };
        /** MetricsOut */
        MetricsOut: {
            /** Metrics */
            metrics: string[];
        };
        /** NarrationStatus */
        NarrationStatus: {
            /**
             * Accepted
             * @default 0
             */
            accepted: number;
            /**
             * Calls
             * @default 0
             */
            calls: number;
            /**
             * Failed
             * @default 0
             */
            failed: number;
            /** Last Error */
            last_error?: string | null;
            /** Mode */
            mode: string;
            /** Model */
            model?: string | null;
            /**
             * Rejected
             * @default 0
             */
            rejected: number;
        };
        /** ObjectiveTerm */
        ObjectiveTerm: {
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Expression */
            expression: string;
            /**
             * Level
             * @enum {string}
             */
            level: "L1" | "L2" | "L3" | "L4";
            /** Name */
            name: string;
            /** Weight */
            weight: number;
        };
        /** ParameterDef */
        ParameterDef: {
            /** Choices */
            choices?: string[] | null;
            /**
             * Default
             * @default 0
             */
            default: unknown;
            /**
             * Description
             * @default
             */
            description: string;
            /** Name */
            name: string;
            /**
             * Scope
             * @default global
             * @enum {string}
             */
            scope: "flight" | "aircraft" | "crew" | "airport" | "itinerary" | "global";
            /**
             * Source
             * @default user
             * @enum {string}
             */
            source: "column" | "user" | "builtin";
            /**
             * Type
             * @default number
             * @enum {string}
             */
            type: "number" | "bool" | "enum" | "text";
            /** Unit */
            unit?: string | null;
        };
        /** PatchRequest */
        PatchRequest: {
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            };
            /** Fields */
            fields?: {
                [key: string]: unknown;
            };
            /** Remove Attributes */
            remove_attributes?: string[];
        };
        /** Plan */
        Plan: {
            /** Actions */
            actions: components["schemas"]["Action"][];
            /** Explanation */
            explanation?: {
                [key: string]: unknown;
            };
            /** Metrics */
            metrics?: {
                [key: string]: number;
            };
            /**
             * Nis
             * @default 0
             */
            nis: number;
            /** Nis Breakdown */
            nis_breakdown?: {
                [key: string]: number;
            };
            /** Rank */
            rank?: number | null;
            scenario_stats?: components["schemas"]["ScenarioStats"] | null;
        };
        /** PlanTimelineRequest */
        PlanTimelineRequest: {
            /** Actions */
            actions: components["schemas"]["Action"][];
            /**
             * Decision Time
             * @default 0
             */
            decision_time: number;
            /** Instance Id */
            instance_id: string;
        };
        /** PolicyOutcomeOut */
        PolicyOutcomeOut: {
            /** Actions */
            actions?: string[];
            /** Delay Min */
            delay_min: number;
            /** Forced */
            forced: number;
            /** Latency Ms */
            latency_ms: number;
            /** Misconnects */
            misconnects: number;
            /** Nis Mean */
            nis_mean: number;
            /** Nis P90 */
            nis_p90: number;
            /** Pax Cancelled */
            pax_cancelled: number;
            /** Pax Stranded */
            pax_stranded: number;
        };
        /** PolicySummaryOut */
        PolicySummaryOut: {
            /** Delay Min Mean */
            delay_min_mean: number;
            /** Forced Mean */
            forced_mean: number;
            /** Improvement Vs B0 Pct */
            improvement_vs_B0_pct: number;
            /** Latency Ms Mean */
            latency_ms_mean: number;
            /** Latency Ms P95 */
            latency_ms_p95: number;
            /** Misconnects Mean */
            misconnects_mean: number;
            /** Nis Mean */
            nis_mean: number;
            /** Nis P90 Mean */
            nis_p90_mean: number;
            /** Pax Cancelled Mean */
            pax_cancelled_mean: number;
            /** Pax Stranded Mean */
            pax_stranded_mean: number;
            /** Tie Rate Vs B0 */
            tie_rate_vs_B0: number;
            /** Win Rate Vs B0 */
            win_rate_vs_B0: number;
        };
        /** PresetRowOut */
        PresetRowOut: {
            /** Hash */
            hash: string;
            /** Name */
            name: string;
            /** Updated At */
            updated_at: string;
            /** Version */
            version: number;
        };
        /** RecommendRequest */
        RecommendRequest: {
            /**
             * Decision Time
             * @default 0
             */
            decision_time: number;
            /** Instance Id */
            instance_id: string;
            /** Previous Run Id */
            previous_run_id?: string | null;
            /**
             * Seed
             * @default 0
             */
            seed: number;
            /** Whatif */
            whatif?: components["schemas"]["Action"][][];
        };
        /** Run */
        Run: {
            /** Accepted Plan */
            accepted_plan?: number | null;
            /** At Risk */
            at_risk?: {
                [key: string]: unknown;
            }[];
            /** Baseline Metrics */
            baseline_metrics?: {
                [key: string]: number;
            };
            /** Committed At */
            committed_at?: string | null;
            /** Config Hash */
            config_hash: string;
            /** Created At */
            created_at: string;
            /** Decision Time */
            decision_time: number;
            /**
             * Depth Reached
             * @default 0
             */
            depth_reached: number;
            /** Effective */
            effective?: {
                [key: string]: unknown;
            };
            /** Engine Version */
            engine_version: string;
            /** Excluded */
            excluded?: components["schemas"]["Action"][];
            /** Id */
            id: string;
            /** Instance Hash */
            instance_hash?: string | null;
            /** Instance Name */
            instance_name: string;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
            /** Narrative */
            narrative?: string | null;
            /** Notes */
            notes?: string[];
            /** Override Reason */
            override_reason?: string | null;
            /** Plans */
            plans: components["schemas"]["Plan"][];
            /**
             * Plans Evaluated
             * @default 0
             */
            plans_evaluated: number;
            /** Whatif */
            whatif?: components["schemas"]["Plan"][];
        };
        /** RunRowOut */
        RunRowOut: {
            /** Accepted Plan */
            accepted_plan?: number | null;
            /** At Risk */
            at_risk: number;
            /** Config Hash */
            config_hash: string;
            /** Created At */
            created_at: string;
            /** Decision Time */
            decision_time: number;
            /** Effective */
            effective?: {
                [key: string]: unknown;
            };
            /** Engine Version */
            engine_version: string;
            /** Id */
            id: string;
            /** Instance Hash */
            instance_hash?: string | null;
            /** Instance Id */
            instance_id: string;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Override Reason */
            override_reason?: string | null;
            /** Plans Evaluated */
            plans_evaluated?: number | null;
            /** Top Nis */
            top_nis?: number | null;
            /** Top Plan */
            top_plan: string[];
        };
        /** ScenarioStats */
        ScenarioStats: {
            /** Mean */
            mean: number;
            /** P90 */
            p90: number;
            /** Samples */
            samples: number;
            /** Stability */
            stability?: number | null;
            /** Values */
            values?: number[];
        };
        /** SearchSettings */
        SearchSettings: {
            /**
             * D
             * @description beam depth (actions per plan)
             * @default 3
             */
            D: number;
            /**
             * K
             * @description beam width
             * @default 5
             */
            K: number;
            /**
             * M
             * @description candidates kept after surrogate pre-rank
             * @default 12
             */
            M: number;
            /**
             * N
             * @description plans re-evaluated under scenarios
             * @default 8
             */
            N: number;
            /**
             * S
             * @description sampled scenarios per plan
             * @default 10
             */
            S: number;
            /**
             * At Risk Delay Threshold Min
             * @default 45
             */
            at_risk_delay_threshold_min: number;
            /**
             * Candidate Scope
             * @default at_risk_only
             * @enum {string}
             */
            candidate_scope: "at_risk_only" | "at_risk_plus_neighbours";
            /** Delay Steps Min */
            delay_steps_min?: number[];
            /**
             * Deterministic
             * @description audit mode: never trade samples or depth for latency, so the same inputs always give the same answer (excluded from the config hash)
             * @default false
             */
            deterministic: boolean;
            /**
             * Forced Cancel Delay Min
             * @description propagation: a leg that cannot depart within this delay is a forced cancellation
             * @default 300
             */
            forced_cancel_delay_min: number;
            /**
             * Horizon Hours
             * @default 8
             */
            horizon_hours: number;
            /**
             * Hysteresis Pct
             * @default 5
             */
            hysteresis_pct: number;
            /**
             * Latency Budget Ms
             * @default 5000
             */
            latency_budget_ms: number;
            /** Level Tolerances */
            level_tolerances?: {
                [key: string]: number;
            };
            /**
             * Max Delay Min
             * @default 180
             */
            max_delay_min: number;
            /**
             * Max Staleness Min
             * @description abstain if inputs older than this
             * @default 30
             */
            max_staleness_min: number;
            /**
             * Post Flight Duty Min
             * @description duty minutes after final on-blocks counted inside the FDP
             * @default 30
             */
            post_flight_duty_min: number;
            /**
             * Ranking Mode
             * @default composite
             * @enum {string}
             */
            ranking_mode: "composite" | "priority";
            /**
             * Standby Hold Min
             * @description max extra wait for a standby crew call-out before the leg is forced-cancelled
             * @default 120
             */
            standby_hold_min: number;
            /**
             * Top N Returned
             * @default 3
             */
            top_n_returned: number;
        };
        /**
         * State
         * @description Operational snapshot at ``clock``: the immutable instance plus the decisions taken so far.
         */
        State: {
            /** Clock */
            clock: number;
            decisions?: components["schemas"]["Decisions"];
            instance: components["schemas"]["Instance"];
        };
        /** TableOut */
        TableOut: {
            /** Attribute Columns */
            attribute_columns?: string[];
            /** Columns */
            columns: string[];
            /** Entity */
            entity: string;
            /** Key */
            key: string;
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
        };
        /** TimeWindow */
        TimeWindow: {
            /** End */
            end: number;
            /** Start */
            start: number;
        };
        /** TimelineFlightOut */
        TimelineFlightOut: {
            /** Aircraft Type */
            aircraft_type: string;
            /** Arr */
            arr?: number | null;
            /** At Risk */
            at_risk: boolean;
            /** Booked Pax */
            booked_pax: number;
            /** Crew Id */
            crew_id?: string | null;
            /** Delay Min */
            delay_min: number;
            /** Dep */
            dep?: number | null;
            /** Dest */
            dest: string;
            /** Id */
            id: string;
            /** Number */
            number: string;
            /** Origin */
            origin: string;
            /** Pax Connecting */
            pax_connecting: number;
            /**
             * Protected
             * @default false
             */
            protected: boolean;
            /** Reason */
            reason?: string | null;
            /** Risk Reasons */
            risk_reasons?: string[];
            /** Sta */
            sta: number;
            /** Sta Hhmm */
            sta_hhmm: string;
            /** Standby Called */
            standby_called: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "OPERATED" | "CANCELLED_DECISION" | "CANCELLED_FORCED" | "PAST";
            /** Std */
            std: number;
            /** Std Hhmm */
            std_hhmm: string;
            /** Tail */
            tail?: string | null;
        };
        /** TimelineOut */
        TimelineOut: {
            /** At Risk */
            at_risk: components["schemas"]["AtRiskOut"][];
            /** Clock */
            clock: number;
            /** Clock Hhmm */
            clock_hhmm: string;
            committed: components["schemas"]["CommittedOut"];
            /** Disruptions */
            disruptions: components["schemas"]["Disruption"][];
            /** Flights */
            flights: components["schemas"]["TimelineFlightOut"][];
            /** Instance Id */
            instance_id: string;
            /** Rotations */
            rotations: {
                [key: string]: string[];
            };
            summary: components["schemas"]["TimelineSummaryOut"];
        };
        /** TimelineSummaryOut */
        TimelineSummaryOut: {
            /** Aircraft Available */
            aircraft_available: number;
            /** At Risk */
            at_risk: number;
            /** Delayed Flights */
            delayed_flights: number;
            /** Flights */
            flights: number;
            /** Forced Cancellations */
            forced_cancellations: number;
            /** Misconnects */
            misconnects: number;
            /** Standby Crews */
            standby_crews: number;
            /** Standby Used */
            standby_used: number;
            /** Stranded Overnight */
            stranded_overnight: number;
            /** Total Delay Min */
            total_delay_min: number;
        };
        /** ValidateRequest */
        ValidateRequest: {
            /** Constraints */
            constraints?: components["schemas"]["ConstraintDef"][] | null;
            /** Terms */
            terms?: components["schemas"]["ObjectiveTerm"][] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WhatIfRequest */
        WhatIfRequest: {
            /** Actions */
            actions: components["schemas"]["Action"][];
            /**
             * Decision Time
             * @default 0
             */
            decision_time: number;
            /** Instance Id */
            instance_id: string;
            /**
             * Seed
             * @default 0
             */
            seed: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    latest_benchmark_benchmark_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkOut"];
                };
            };
        };
    };
    run_bench_benchmark_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BenchmarkRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cases_cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDefOut"][];
                };
            };
        };
    };
    latest_cases_cases_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CasesRunOut"];
                };
            };
        };
    };
    run_cases_cases_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CasesRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CasesRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigEnvelope"];
                };
            };
        };
    };
    put_constraints_config_constraints_put: {
        parameters: {
            query?: never;
            header?: {
                "x-aeronexus-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConstraintDef"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_hash_config_hash_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    metric_names_config_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsOut"];
                };
            };
        };
    };
    put_parameters_config_parameters_put: {
        parameters: {
            query?: never;
            header?: {
                "x-aeronexus-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParameterDef"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plugins_config_plugins_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    presets_config_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetRowOut"][];
                };
            };
        };
    };
    save_preset_config_presets__name__post: {
        parameters: {
            query?: never;
            header?: {
                "x-aeronexus-key"?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_preset_config_presets__name__load_post: {
        parameters: {
            query?: never;
            header?: {
                "x-aeronexus-key"?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_from_yaml_config_reset_post: {
        parameters: {
            query?: never;
            header?: {
                "x-aeronexus-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_search_config_search_put: {
        parameters: {
            query?: never;
            header?: {
                "x-aeronexus-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchSettings"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_terms_config_terms_put: {
        parameters: {
            query?: never;
            header?: {
                "x-aeronexus-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObjectiveTerm"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_config_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_instance_data_generate_post: {
        parameters: {
            query?: never;
            header?: {
                "x-aeronexus-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_instance_data_import_post: {
        parameters: {
            query?: never;
            header?: {
                "x-aeronexus-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Instance"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_instances_data_instances_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceRowOut"][];
                };
            };
        };
    };
    get_instance_data_instances__iid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                iid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instance"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_instance_data_instances__iid__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-aeronexus-key"?: string | null;
            };
            path: {
                iid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_column_data_instances__iid__columns_post: {
        parameters: {
            query?: never;
            header?: {
                "x-aeronexus-key"?: string | null;
            };
            path: {
                iid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ColumnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_committed_data_instances__iid__committed_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                iid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommittedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_committed_data_instances__iid__committed_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                iid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommittedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_disruption_data_instances__iid__disruptions_post: {
        parameters: {
            query?: never;
            header?: {
                "x-aeronexus-key"?: string | null;
            };
            path: {
                iid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisruptionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_disruption_data_instances__iid__disruptions__did__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-aeronexus-key"?: string | null;
            };
            path: {
                iid: string;
                did: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summary_data_instances__iid__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                iid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    table_data_instances__iid__table__entity__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                iid: string;
                entity: "flights" | "aircraft" | "crews" | "airports" | "itineraries";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_row_data_instances__iid___entity___key__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-aeronexus-key"?: string | null;
            };
            path: {
                iid: string;
                entity: "flights" | "aircraft" | "crews" | "airports" | "itineraries";
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    post_recommend_recommend_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_runs_get: {
        parameters: {
            query?: {
                instance_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRowOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_runs__run_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_state_state_get: {
        parameters: {
            query: {
                instance_id: string;
                t?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["State"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timeline_timeline_get: {
        parameters: {
            query: {
                instance_id: string;
                t?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_timeline_timeline_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanTimelineRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_whatif_whatif_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhatIfRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
